### ISSUE TITLE
1차 DB 설계

### ISSUE THREAD

**Issue by ugaemi** [ugaemi/emariya#1]
[ERDCloud](https://www.erdcloud.com/) 이용

**Comment by ugaemi** [comment]
![이말이야](https://user-images.githubusercontent.com/39613477/68023493-8d056a80-fcea-11e9-9f45-c79052e6ad03.png)

**Comment by twowix** [comment]
![emal-erd](https://user-images.githubusercontent.com/15812677/68035623-5a1d9f80-fd07-11e9-9bea-1a453634741e.png)
